export type ReplyStyle = "friendly" | "funny" | "romantic" | "confident" | "short" | "long";
export type PickupCategory = "Funny" | "Romantic" | "Cute" | "Bold" | "Smooth" | "First Message" | "Ice Breaker";
export type StarterCategory = "Friends" | "Dating" | "Crush" | "WhatsApp" | "Instagram" | "Facebook" | "Random";
export type StatusCategory = "WhatsApp Status" | "Facebook Caption" | "Instagram Caption" | "TikTok Caption" | "Motivational Quotes" | "Love Quotes" | "Funny Status" | "Friendship Status" | "Success Quotes";

const replyOpeners: Record<ReplyStyle, string[]> = {
  friendly: ["That sounds real", "I appreciate you saying that", "I can see where you are coming from", "That gave me a little context", "Thanks for being open", "I like that you shared that", "That makes sense to me", "I hear the feeling behind that", "You make a fair point", "I am glad you told me", "That is thoughtful", "I get why that landed with you", "That is worth talking about", "I like your honesty", "I can meet you there", "That is a good way to put it", "I am listening", "That feels relatable", "I respect that", "You have my attention"],
  funny: ["Plot twist", "Emergency update", "I have consulted the board", "This is getting suspiciously interesting", "My extremely serious opinion", "Breaking news", "I am trying to act normal about this", "The plot is thickening", "Respectfully, this has main-character energy", "I was not emotionally prepared for that", "My charm department has been notified", "That deserves a tiny victory dance", "I need a moment to process this plot twist", "You cannot just say that and disappear", "I am filing this under excellent conversation", "The committee agrees", "I have questions and a snack", "This is exactly the kind of chaos I support", "I am impressed and mildly concerned", "My inner narrator is delighted"],
  romantic: ["That made me smile", "I like the way you see things", "There is something warm about that", "You have a way of making a moment feel softer", "That landed beautifully", "I keep thinking about that", "I like being in this conversation with you", "That is unexpectedly sweet", "You make honesty feel easy", "I am enjoying your energy", "That felt genuine", "You have a lovely perspective", "That gave me a quiet little smile", "I like where this conversation is going", "That is the kind of detail I notice", "You make simple things feel memorable", "That feels refreshingly real", "I like your heart in that", "You just made this chat better", "That is a beautiful thought"],
  confident: ["I like clarity", "I am glad we can be direct", "Here is my honest take", "I know what I enjoy", "That is fair", "I respect a clear conversation", "I am not here to play guessing games", "I value good energy", "I can be straightforward about this", "I appreciate the honesty", "I know the pace that works for me", "I would rather be genuine than perform", "I am comfortable saying this", "I like intentional conversations", "I trust a calm approach", "I am interested in something real", "I believe in meeting energy with energy", "I am happy to keep this simple", "I know what feels right to me", "I am open, but I am grounded"],
  short: ["I get that", "Fair point", "That made me smile", "I am with you", "Tell me more", "I like that", "That is real", "I hear you", "Good energy", "I respect it", "That is sweet", "I am curious", "You have my attention", "That works for me", "I like your honesty", "Interesting", "That is thoughtful", "I am listening", "Nice", "Absolutely"],
  long: ["Thanks for saying that", "I appreciate the honesty", "I want to respond thoughtfully", "I like that we can talk about this", "That is worth slowing down for", "I hear what you are really saying", "I can understand the feeling behind that", "I am glad you brought it up", "I want to be clear with you too", "That gives this conversation more depth", "I value how open you are being", "I do not want to rush past that", "That feels important", "I like conversations with this kind of honesty", "I can see why that matters to you", "I am taking that in", "I want to meet that with sincerity", "That deserves a real answer", "I like that you trust me enough to say it", "You just gave me something genuine to respond to"],
};

const replyHooks: Record<ReplyStyle, string[]> = {
  friendly: ["what part mattered most to you?", "how did that feel from your side?", "what would make the next step easier?", "I would love to hear the full version.", "what happened after that?", "where is your head at now?", "what are you hoping for?", "tell me the part people usually miss.", "how can I support the conversation?", "I am curious what you want next.", "what would feel good right now?", "how do you want to handle it?", "give me the honest version.", "what do you wish they understood?", "what feels most important here?"],
  funny: ["are we admitting this is a good sign yet?", "should I pretend I am not impressed?", "what is the next episode called?", "do I get credit for staying calm?", "is this where I say something effortlessly charming?", "should we make this our official inside joke?", "are you always this entertaining?", "what is the proper celebratory emoji for this?", "do I need to prepare a sequel?", "can we agree this deserves better than a basic reply?", "is there a trophy for this conversation?", "what is your defense, counselor?", "should I be taking notes?", "do we tell the group chat?", "is this your usual level of iconic?"],
  romantic: ["what is on your mind beneath the surface?", "I would love to know more about you.", "how did that moment feel for you?", "tell me the story behind that smile.", "what would make today feel a little better?", "what are you hoping this becomes?", "I like hearing the details that matter to you.", "what is the part you have not said out loud?", "where would you take this conversation next?", "what makes you feel most understood?", "what would feel thoughtful to you?", "what is something you wish more people noticed?", "how can I make this easier to talk about?", "what is your favorite part of that memory?", "what are you feeling right now?"],
  confident: ["I would rather ask than assume: what do you want?", "I am interested in a clear answer.", "what does a good next step look like to you?", "I am open to seeing where this goes.", "let us keep the energy honest.", "what are you actually hoping for here?", "I like a conversation with direction.", "I can match effort, not mixed signals.", "what feels intentional to you?", "I am here for a good conversation, not confusion.", "where do you want to take this?", "I want something easy and respectful.", "what would be true for you?", "I am happy to make a plan if you are.", "let us be clear and enjoy it."],
  short: ["What do you think?", "Tell me more.", "How did that go?", "I am curious.", "What is next?", "That is nice.", "I like the sound of that.", "Go on.", "I hear you.", "Fair enough.", "That tracks.", "I am interested.", "Keep going.", "What happened?", "I am here."],
  long: ["I do not want to make assumptions, so tell me what you need most from this conversation. I am happy to listen first and be honest after.", "I want this to feel easy, not like either of us has to perform. What is the one thing you want me to understand about it?", "I like directness with a little warmth, so I will say this plainly: I am engaged in the conversation. What feels like the right next move to you?", "It sounds like there is more underneath that. If you are comfortable, tell me the detail that would help me understand your point of view better.", "I appreciate the chance to be real about this. I am not looking for a perfect answer; I am looking for an honest one. What are you feeling right now?", "I want to match your openness with mine. Let us keep it simple and kind: what would make you feel heard here?", "There is no need to rush a good conversation. I am curious about the story behind that and what you hope happens next.", "I like that this has a little depth. I am listening, and I would rather respond to the real thing than guess at it. What is the important part for you?", "Thanks for trusting me with that. I can see why it would matter, and I would love to know how you want to move through it.", "I enjoy conversations where both people can be honest without pressure. What would a good outcome feel like to you?", "I am glad you said it instead of keeping it in your head. I am here, and I would like to understand what you need from me.", "I do not need a polished answer from you. The real version is more interesting. What has been sitting with you?", "You are allowed to take up space in this conversation. I am interested in what you think, and I want to hear the part that feels most true.", "I like the energy of being clear without making things heavy. What is one thing you would want us to be honest about?", "I want to respond with care, not just speed. Tell me what would make this feel better or more natural for you."],
};

function crossJoin(first: string[], second: string[], target: number) {
  return Array.from({ length: target }, (_, index) => `${first[index % first.length]} — ${second[Math.floor(index / first.length) % second.length]}`);
}

export const replyLibraries: Record<ReplyStyle, string[]> = {
  friendly: crossJoin(replyOpeners.friendly, replyHooks.friendly, 300),
  funny: crossJoin(replyOpeners.funny, replyHooks.funny, 300),
  romantic: crossJoin(replyOpeners.romantic, replyHooks.romantic, 300),
  confident: crossJoin(replyOpeners.confident, replyHooks.confident, 300),
  short: crossJoin(replyOpeners.short, replyHooks.short, 200),
  long: crossJoin(replyOpeners.long, replyHooks.long, 200),
};

const pickupAngles = ["your timing", "that smile", "your energy", "your taste", "your sense of humor", "your confidence", "your playlist potential", "the way you show up", "your curiosity", "your vibe", "your laugh", "your perspective", "your style", "your warmth", "your spark"];
const pickupHooks: Record<PickupCategory, string[]> = {
  Funny: ["should come with a warning label", "has made my inner comedian nervous", "might be too good for a normal opener", "is making this feel suspiciously easy", "deserves a five-star review", "has me drafting a sequel already", "could turn a Tuesday into an event", "is clearly causing a little chaos", "is not something I can scroll past", "makes small talk feel wildly underqualified"],
  Romantic: ["feels like a detail worth remembering", "has the kind of warmth people notice", "makes a simple hello feel special", "could make an ordinary day softer", "has me curious about your story", "feels quietly unforgettable", "makes this conversation feel lighter", "is the kind of thing I would linger over", "has a calm kind of magic", "makes me want to know you better"],
  Cute: ["is honestly adorable", "just earned a small happy dance", "might be my favorite thing today", "would make a great reason to smile", "is exactly the right kind of sweet", "has me grinning at my screen", "deserves a tiny celebration", "is too charming to ignore", "just made this chat cuter", "could brighten a whole afternoon"],
  Bold: ["has me thinking we should skip the boring part and get coffee", "makes me want to be direct: I would like to know you", "is a good reason to plan something fun", "has earned an honest question: when are you free?", "makes a confident hello feel appropriate", "is why I think a real conversation would be better", "deserves more than a like from me", "makes me want to see if the chemistry is real", "is a great argument for a first date", "has my attention, and I do not give that away casually"],
  Smooth: ["makes this opener feel almost too easy", "is the kind of detail that makes a chat flow", "has a way of raising the standard", "makes me curious in the best way", "is the start of a promising conversation", "feels like a good reason to say hello", "has me wondering what else I would notice", "makes confident conversation look effortless", "has a very hard-to-ignore rhythm", "makes this feel like the right moment to introduce myself"],
  "First Message": ["felt like the right reason to say hello", "made a first message feel worth sending", "gave me an easy excuse to introduce myself", "stood out enough to stop the scroll", "is exactly why I am saying hi", "made me curious enough to reach out", "deserves more than a silent like", "gave this message a good opening line", "made me wonder what you are like off-screen", "is a solid reason to start a conversation"],
  "Ice Breaker": ["is perfect for a quick question", "has me wondering what your answer would be", "is making me choose curiosity over small talk", "would make a fun two-minute debate", "is an excellent first clue about you", "could settle an important question for me", "is the kind of thing I would love to ask about", "makes an ice breaker feel less awkward", "has me ready with one interesting question", "is a promising place to start"],
};

export const pickupLibraries: Record<PickupCategory, string[]> = Object.fromEntries(
  (Object.keys(pickupHooks) as PickupCategory[]).map((category) => [category, crossJoin(pickupAngles.map((angle) => `I have to say, ${angle}`), pickupHooks[category], 150)]),
) as Record<PickupCategory, string[]>;

const starterThemes = ["a small win from this week", "a comfort show", "a perfect weekend", "a song you cannot skip", "a hidden talent", "a childhood favorite", "a great food opinion", "a travel story", "a tiny thing that makes you laugh", "a goal you are quietly working on", "a place that feels like home", "a hobby you want to try", "a very specific green flag", "the best kind of surprise", "a memory you would replay"];
const starterFrames = ["What is your take on {theme}?", "I need your expert opinion: {theme}?", "Tell me about {theme}.", "What is the story behind {theme}?", "How would you describe {theme} to someone new?", "What is one underrated thing about {theme}?", "If we were talking for an hour, would {theme} come up?", "What would make {theme} even better?"];

export const starterLibraries: Record<StarterCategory, string[]> = Object.fromEntries(
  (["Friends", "Dating", "Crush", "WhatsApp", "Instagram", "Facebook", "Random"] as StarterCategory[]).map((category) => [category, Array.from({ length: 120 }, (_, index) => {
    const theme = starterThemes[index % starterThemes.length];
    const frame = starterFrames[Math.floor(index / starterThemes.length) % starterFrames.length];
    return `${frame.replace("{theme}", theme)} ${category === "Dating" || category === "Crush" ? "I am genuinely curious." : ""}`.trim();
  })]),
) as Record<StarterCategory, string[]>;

const statusMoods = ["soft heart", "calm confidence", "quiet progress", "good energy", "strong standards", "fresh perspective", "slow mornings", "big dreams", "real peace", "bright thoughts", "grateful spirit", "gentle strength", "bold growth", "private joy", "clear intentions", "kind boundaries", "creative spark", "steady focus", "warm memories", "main-character energy"];
const statusClosers = ["moving with purpose.", "becoming more myself every day.", "and leaving room for good surprises.", "with no need to rush the magic.", "while choosing what feels true.", "and protecting my peace.", "one intentional moment at a time.", "with a little sparkle on the side.", "and a heart open to good things.", "without shrinking to fit old rooms.", "with a grateful mind and a brave heart.", "and making the ordinary feel special.", "while letting the right things grow.", "with more courage than yesterday.", "and a story still unfolding."];

export const statusLibraries: Record<StatusCategory, string[]> = Object.fromEntries(
  (["WhatsApp Status", "Facebook Caption", "Instagram Caption", "TikTok Caption", "Motivational Quotes", "Love Quotes", "Funny Status", "Friendship Status", "Success Quotes"] as StatusCategory[]).map((category) => [category, Array.from({ length: 300 }, (_, index) => {
    const mood = statusMoods[index % statusMoods.length];
    const closer = statusClosers[Math.floor(index / statusMoods.length) % statusClosers.length];
    const prefix = category === "Funny Status" ? "Current status: professionally unserious, " : category === "Love Quotes" ? "Love looks like " : category === "Friendship Status" ? "Good friends bring " : category === "Success Quotes" ? "Success is " : category === "Motivational Quotes" ? "Reminder: " : "";
    return `${prefix}${mood}, ${closer}`;
  })]),
) as Record<StatusCategory, string[]>;

const insightSkills = ["curiosity", "calm confidence", "active listening", "warm boundaries", "clear texting", "playful flirting", "self-respect", "emotional honesty", "patience", "body language", "first-date energy", "relationship repair", "friendship care", "social courage", "thoughtful follow-up", "conversation balance", "healthy space", "kind directness", "self-esteem", "long-distance connection", "marriage teamwork", "breakup healing", "WhatsApp rhythm", "complimenting", "being present"];
const insightFrames = ["Practice {skill} by choosing one small, specific action today.", "The fastest way to strengthen {skill} is to slow down and be intentional.", "When {skill} feels hard, make your next move simpler rather than bigger.", "Healthy {skill} often sounds warm, clear, and easy to answer.", "Build {skill} through repetition, not perfection.", "A good check-in can turn {skill} into connection.", "Let {skill} be a choice you make for yourself, not a performance for someone else.", "The most attractive version of {skill} is respectful and grounded.", "Notice where you already show {skill}; confidence grows from evidence.", "Use one honest question to practice {skill} today.", "Strong {skill} leaves room for the other person to be themselves.", "Give yourself permission to learn {skill} one conversation at a time.", "If you are unsure, choose kindness first; it supports {skill}.", "Small moments of {skill} create the strongest social habits.", "Your next chance to practice {skill} may be a simple hello."];

export const dailyInsights = Array.from({ length: 365 }, (_, index) => insightFrames[Math.floor(index / insightSkills.length) % insightFrames.length].replace("{skill}", insightSkills[index % insightSkills.length]));

export function selectLibraryItem(library: string[], counter: number, context = "") {
  const normalized = context.trim().replace(/\s+/g, " ").slice(-90);
  const hash = [...normalized].reduce((sum, char) => sum + char.charCodeAt(0), 0);
  return library[(hash + counter) % library.length];
}

export function replySet(context: string, counter: number) {
  return {
    friendly: selectLibraryItem(replyLibraries.friendly, counter, context),
    funny: selectLibraryItem(replyLibraries.funny, counter + 17, context),
    romantic: selectLibraryItem(replyLibraries.romantic, counter + 41, context),
    confident: selectLibraryItem(replyLibraries.confident, counter + 73, context),
    short: selectLibraryItem(replyLibraries.short, counter + 101, context),
    long: selectLibraryItem(replyLibraries.long, counter + 131, context),
  };
}
