export type CoachTopic = "dating" | "relationships" | "flirting" | "confidence" | "social-anxiety" | "breakups" | "friendships" | "communication" | "texting" | "whatsapp" | "first-dates" | "marriage" | "long-distance" | "self-esteem" | "body-language";

export type CoachMemory = {
  userName?: string;
  goals: string[];
  confidenceLevel: "building" | "steady" | "strong";
  favoriteTopics: CoachTopic[];
  relationshipStatus?: string;
  xp?: number;
  achievements?: string[];
  recentResponses: string[];
};

export type CoachTurn = { role: "user" | "coach" | "practice"; text: string; time?: string };

const topicProfiles: Record<CoachTopic, { markers: string[]; focus: string; actions: string[]; questions: string[] }> = {
  dating: { markers: ["dating", "date", "seeing someone", "match", "app", "tinder", "bumble"], focus: "dating with calm clarity", actions: ["choose one specific invitation instead of vague hints", "lead with curiosity before trying to impress", "match effort rather than chasing uncertainty", "keep your standards visible and your tone warm", "suggest a simple plan with an easy yes-or-no", "notice whether their actions match their words", "let the conversation build before over-investing", "be honest about what kind of connection you want", "make room for playfulness without performing", "look for comfort as well as chemistry", "use a clear compliment based on something real", "avoid turning every pause into a verdict", "treat compatibility as something you discover together", "choose a pace that keeps you grounded", "keep the next step light and concrete", "make your interest clear without making it heavy"], questions: ["What would a comfortable next step look like for you?", "What have they done that makes you feel at ease?", "Are you looking for chemistry, consistency, or both right now?", "What would you say if you trusted yourself a little more?", "What boundary would help you enjoy this more?", "What is one detail you genuinely like about them?", "How do you want to feel after the next conversation?", "What are you learning about their effort?", "Would a simple plan remove the guessing?", "What is your own green flag in this situation?", "What would calm confidence sound like here?", "What are you hoping to learn before you invest more?", "What part feels exciting and what part feels uncertain?", "What would make the next message easy to answer?", "How can you stay curious instead of outcome-focused?", "What does a healthy pace feel like in your body?"] },
  relationships: { markers: ["relationship", "partner", "boyfriend", "girlfriend", "couple", "together"], focus: "building trust and repair", actions: ["name the feeling before debating the details", "ask for the need underneath the complaint", "use a calm check-in rather than a loaded accusation", "choose one repair attempt instead of reopening every old issue", "say what you appreciate before raising a concern", "make room for two truths at once", "set a time to talk when both of you can be present", "replace mind-reading with a specific question", "notice patterns without turning them into character attacks", "ask for a small behavioral change you can both understand", "protect warmth during difficult conversations", "pause before responding when your nervous system is activated", "make agreements that are observable and kind", "speak from your experience rather than assigning motives", "ask what support would feel meaningful", "end the conversation with a concrete next step"], questions: ["What do you need them to understand, not just agree with?", "What would repair look like in one small action?", "When do you feel most connected to them?", "What are you both trying to protect in this moment?", "What tone would help this conversation stay safe?", "What request can you make without blame?", "What part of this is a pattern versus a one-off moment?", "What would help you feel heard today?", "What agreement would reduce the same conflict next week?", "Where can you offer appreciation honestly?", "What would you want them to ask you right now?", "What feels vulnerable to say but important?", "How could you slow this down without avoiding it?", "What does trust need from both of you here?", "What is one thing you can own without taking all the responsibility?", "How would you know the conversation went well?" ] },
  flirting: { markers: ["flirt", "flirting", "chemistry", "tease", "playful"], focus: "playful, respectful connection", actions: ["notice a real detail and make a light compliment", "use a playful observation that gives them room to respond", "keep the energy reciprocal instead of escalating alone", "ask a fun question with no pressure attached", "let a little pause create space for them to lean in", "match their level of warmth before turning it up", "use curiosity rather than a rehearsed line", "keep your compliments specific and believable", "make a confident suggestion without demanding an answer", "invite banter rather than trying to win the exchange", "respect a slow response without filling the silence", "look for enthusiasm, not just politeness", "make the other person feel seen rather than evaluated", "use humor that includes rather than teases at their expense", "keep your self-respect visible", "treat consent and comfort as part of the charm"], questions: ["What detail about them could you mention naturally?", "Are they matching your playful energy?", "What would a low-pressure next line sound like?", "How can you make this more about connection than performance?", "What signal of enthusiasm have you noticed?", "Would a specific compliment feel more genuine here?", "Can you leave them an easy opening to respond?", "What would be playful without being confusing?", "How can you keep this light and respectful?", "What would your calmest confident version say?", "Are you giving them enough space to choose?", "What could make them smile without putting them on the spot?", "What part of their energy genuinely interests you?", "Would less be more in this moment?", "What boundary keeps this fun for both people?", "How can you show interest without a script?" ] },
  confidence: { markers: ["confidence", "confident", "awkward", "impress", "shy"], focus: "quiet confidence", actions: ["choose a smaller brave action instead of waiting to feel fearless", "replace self-criticism with one neutral observation", "say one clear sentence before adding explanation", "let your pace slow down enough for your words to land", "make eye contact for one extra breath", "focus on being interested instead of impressive", "remember evidence of times you handled things well", "speak from preference rather than apology", "practice a simple opener until it feels familiar", "allow yourself to take up conversational space", "use posture to remind your body that you are safe", "make one honest request without over-qualifying it", "treat discomfort as practice rather than proof you cannot do it", "choose a realistic goal for this interaction", "notice your strengths before the conversation starts", "give yourself credit for showing up"], questions: ["What is the smallest brave move available right now?", "What would you say if you did not need to be perfect?", "What evidence says you can handle this?", "Where are you already more capable than you give yourself credit for?", "What would calm confidence sound like in one sentence?", "How can you make the goal connection instead of approval?", "What can you control in the next two minutes?", "What do you want to remember about yourself afterward?", "What is one preference you can state clearly?", "What would you try if the stakes felt lower?", "How can you support your nervous system before speaking?", "What would a kind inner coach tell you?", "What are you learning by practicing this?", "How can you keep your posture open and relaxed?", "What does enough look like for today?", "What would help you trust your first sentence?" ] },
  "social-anxiety": { markers: ["social anxiety", "anxiety", "anxious", "nervous", "panic", "overthinking"], focus: "steady, manageable social courage", actions: ["ground yourself through one slow exhale before you respond", "set a two-minute goal instead of trying to solve the whole event", "prepare one simple question and one exit line", "look for one safe person or familiar detail in the room", "name the sensation without treating it as danger", "give yourself permission to pause before answering", "shift attention from your performance to the other person’s story", "use a calm physical anchor such as both feet on the floor", "make a small plan for recovery after the interaction", "allow a quiet moment without apologizing for it", "choose a lower-pressure setting when you can", "practice with tiny exposures rather than all-or-nothing leaps", "reduce caffeine or rushed transitions before a social moment", "remind yourself that awkwardness is survivable", "step outside briefly if you need to reset", "measure courage by action, not comfort"], questions: ["What is one tiny social action that feels doable?", "Where in your body do you notice the anxiety first?", "What would help your nervous system feel safer right now?", "Who or what could be your anchor in this setting?", "What is a kind exit line you can keep ready?", "How can you make the next minute easier?", "What would you say to a friend feeling this way?", "What part of the situation is your mind predicting rather than observing?", "Can you give yourself permission to be quiet and present?", "What is one question you could ask instead of trying to perform?", "How could you celebrate the effort afterward?", "What small exposure would build trust with yourself?", "What does a successful interaction mean if perfection is not required?", "Can you slow your breathing by one count?", "What support would make this feel less lonely?", "What would help you leave with pride, even if it is brief?" ] },
  breakups: { markers: ["breakup", "break up", "ex", "heartbroken", "heartbreak", "miss them"], focus: "healing with self-respect", actions: ["let the feeling be present without turning it into a command", "create a small no-contact boundary that gives your mind room to settle", "write what you miss alongside what was not working", "tell one trusted person what today feels like", "make one decision that cares for your future self", "avoid using a lonely evening as evidence that you made the wrong choice", "remove one trigger that keeps reopening the wound", "allow grief and relief to coexist", "build a new ritual into the time that feels emptiest", "separate the person from the hope you had for the relationship", "return attention to your routines, sleep, and food", "write an unsent message instead of sending an impulse text", "notice what you are learning about your needs", "choose compassionate language when you talk to yourself", "protect your healing from social media spirals", "ask for professional support if the pain feels unmanageable"], questions: ["What do you miss: the person, the routine, or the future you imagined?", "What boundary would give your heart a little more quiet?", "What was true about the relationship that you do not want to forget?", "What would support look like tonight?", "What is one thing you can do that is only for you?", "What are you grieving, and what are you reclaiming?", "Who can remind you of who you are outside this relationship?", "What would a gentle next week look like?", "What part of healing needs patience rather than a solution?", "What do you want future love to feel like?", "What is one trigger you can soften today?", "What would you say in an unsent letter?", "What need are you learning to take seriously?", "What tells you you are moving, even slowly?", "How can you make room for joy without guilt?", "What kind of closure can you give yourself?" ] },
  friendships: { markers: ["friend", "friendship", "bestie", "buddy", "group chat"], focus: "reciprocal friendship", actions: ["reach out with one specific memory or invitation", "say the small appreciation you usually assume they know", "ask a real question and leave time for the answer", "notice whether effort is shared over time", "address a hurt before it turns into distance", "make room for different seasons of availability", "set a boundary without making it a punishment", "plan a low-pressure ritual that keeps connection alive", "be honest about what you can offer right now", "apologize clearly when you miss the mark", "avoid keeping score while still noticing patterns", "celebrate their win without minimizing your own needs", "invite them into something simple and specific", "give the friendship room to change without treating it as failure", "ask for clarity instead of building a story from silence", "choose friends who let you be fully yourself"], questions: ["What would a caring check-in sound like?", "What do you value most about this friendship?", "Is there a small hurt that needs a calm conversation?", "What kind of effort would feel reciprocal to you?", "How can you make the invitation easy to accept?", "What boundary would protect the friendship rather than end it?", "What do you need more of from your circle?", "Who makes you feel most like yourself?", "How can you show appreciation without making it heavy?", "What is one shared ritual you would enjoy?", "What would you say if you trusted the friendship?", "Are you assuming intent where a question would help?", "What does a balanced friendship look like to you?", "How can you be supportive without abandoning your own needs?", "What would repair look like in one sentence?", "Who could use a warm message from you today?" ] },
  communication: { markers: ["communication", "communicate", "argument", "misunderstanding", "talk about"], focus: "clear, compassionate communication", actions: ["lead with the feeling and the specific event", "make one request at a time", "reflect back what you heard before offering your view", "replace blame with a description of impact", "ask whether it is a good time for a real conversation", "keep your message shorter than your first draft", "use a warm tone without abandoning your point", "define what would count as a helpful next step", "ask a question when you notice yourself assuming", "separate facts from the story your mind made around them", "pause when the goal turns from understanding to winning", "name the repair you need", "use an example instead of a global statement", "state your boundary as what you will do", "leave space for the other person’s reality", "end with the clearest next action"], questions: ["What is the simplest true sentence here?", "What impact do you want them to understand?", "What would you ask for if you removed the blame?", "Is this the right time or just the most emotional time?", "What did you hear them say beneath the words?", "What is a concrete example that explains your point?", "What boundary are you trying to communicate?", "How can you make this easier to receive?", "What part is fact and what part is interpretation?", "What would repair look like?", "What do you want the conversation to accomplish?", "Where can you be both direct and kind?", "What question could interrupt the misunderstanding?", "What can wait until you are calmer?", "What do you need to say once, clearly?", "How will you know you both understood each other?" ] },
  texting: { markers: ["text", "texting", "message", "reply", "left on read", "dm"], focus: "texting with rhythm and self-respect", actions: ["acknowledge their message before changing the topic", "use one easy-to-answer question rather than three", "match their energy without shrinking your own voice", "leave room between messages when the conversation is quiet", "choose clarity over trying to sound perfectly clever", "send the message you mean, then let it breathe", "make your invitation specific and low-pressure", "use a warm statement before a question", "avoid reading a whole story into a delayed reply", "keep your message length proportional to the moment", "let consistency matter more than a single perfect text", "use humor as an invitation, not a test", "say what you want instead of hinting until you feel frustrated", "turn a looping chat into a simple plan when it feels right", "take a pause before sending an emotional draft", "give yourself permission to stop carrying the whole conversation"], questions: ["What response would be easy for them to answer?", "Are you responding to their actual message or your worry about it?", "What would a clear invitation look like?", "Can you turn this into one warm sentence and one question?", "What are they showing you through consistency?", "Would waiting ten minutes help you send the message you mean?", "What tone do you want this chat to have?", "Is there a simple next step you can suggest?", "What would you write if you trusted your value?", "How can you give them room to reciprocate?", "What are you hoping a text will solve?", "Would a voice note or plan be clearer here?", "What is the lightest honest version of your thought?", "What does their pace tell you without over-interpreting?", "What message would leave you feeling proud regardless of the reply?", "Can you put your phone down after sending it?" ] },
  whatsapp: { markers: ["whatsapp", "blue tick", "online", "voice note", "status"], focus: "reading WhatsApp context without spiraling", actions: ["treat blue ticks as information, not a verdict", "use a short voice note when tone matters more than speed", "reply to the substance of their message rather than the timestamp", "keep group-chat energy playful and inclusive", "use a status as a light prompt, not a pressure tactic", "write a clear follow-up instead of sending multiple question marks", "give someone time to reply before changing your story about them", "notice whether your chat is balanced over several days", "use a warm opener when restarting an old conversation", "avoid monitoring online status as a measure of interest", "choose a direct message when a reaction needs context", "make plans in the chat rather than endlessly circling", "keep an emotional message in drafts for a few minutes", "send one thoughtful response instead of a burst of fragments", "remember that busy people can still care", "let your boundaries guide when you stop double-texting"], questions: ["What do you actually know beyond the blue ticks?", "Would a voice note make your tone clearer?", "What is the simplest follow-up you could send?", "Are you checking the app for information or reassurance?", "What would a balanced chat feel like this week?", "Can you make the next message lighter and easier to answer?", "Would a clear plan reduce the endless messaging?", "What part of their actual words can you respond to?", "What does your own boundary say about sending another message?", "Can you wait until you feel calmer before replying?", "What does a respectful pause look like?", "Would a warm status reply feel natural here?", "How can you keep the group chat inclusive?", "What tone do you want your message to carry?", "What would help you avoid over-reading online indicators?", "Is there a kinder explanation for the delay?" ] },
  "first-dates": { markers: ["first date", "first-date", "coffee date", "meet them", "date night"], focus: "a relaxed, curious first-date experience", actions: ["choose a setting where conversation is easy", "prepare two curious questions and let the rest be natural", "arrive with the goal of learning, not securing an outcome", "notice how your body feels around them", "make a specific compliment when it is genuine", "share a little about yourself instead of interviewing them", "let silence be a normal part of meeting someone", "keep your plan simple enough to leave room for choice", "check in with your own comfort as much as their interest", "ask about values through stories rather than a checklist", "give yourself permission to leave if the energy is not right", "follow up with a clear, kind message after", "wear something that lets you feel like yourself", "avoid over-rehearsing and focus on being present", "notice how they treat other people", "make the next step optional and concrete"], questions: ["What would help you feel comfortable before you go?", "What are you genuinely curious to learn about them?", "What setting brings out your relaxed side?", "How do you want to feel when the date ends?", "What would make this a win even without chemistry?", "What question would reveal how they see the world?", "What boundary helps you stay grounded?", "How can you be yourself instead of performing?", "What would a simple follow-up sound like?", "What detail would you like them to know about you?", "What does respect look like on this date?", "How can you stay in the moment rather than grading it?", "What is your exit plan if you need one?", "What does curiosity look like in your body language?", "What would help you enjoy the process?", "What is one green flag you want to notice?" ] },
  marriage: { markers: ["marriage", "married", "spouse", "husband", "wife"], focus: "partnership, repair, and everyday connection", actions: ["make a small daily bid for connection", "talk about the problem as something you face together", "say thank you for ordinary efforts", "schedule a check-in before resentment builds", "protect time for affection that is not transactional", "name practical needs clearly", "share the mental load rather than waiting to be asked", "repair quickly after a sharp moment", "create rituals that make home feel like a team", "discuss finances, intimacy, and logistics with curiosity", "avoid keeping score during a stressful season", "ask what support would feel useful today", "make room for both individuality and partnership", "choose appreciation before advice when possible", "return to a shared value when you feel stuck", "use a pause instead of saying something you will have to repair later"], questions: ["What would help you feel like a team this week?", "What daily effort deserves appreciation?", "What practical request have you not made clearly?", "How could you make room for connection without adding pressure?", "What would repair look like after this disagreement?", "What is each of you carrying right now?", "What ritual would make home feel warmer?", "What do you want your partner to understand about your stress?", "How can you approach this as a shared problem?", "What does quality time mean to each of you?", "What boundary would protect the relationship from outside stress?", "What can you thank them for today?", "What needs a calm scheduled conversation?", "What value do you both want to return to?", "How can you ask for affection or help directly?", "What would make the next conversation feel safer?" ] },
  "long-distance": { markers: ["long distance", "long-distance", "far away", "different country", "distance relationship"], focus: "intentional long-distance connection", actions: ["build a realistic rhythm for calls and messages", "share small daily moments instead of saving everything for one call", "make the next visit or shared milestone concrete when possible", "say when you need reassurance instead of testing for it", "create a ritual you can both look forward to", "leave room for separate lives without treating it as distance", "use video or voice when text cannot carry the emotion", "talk openly about expectations around time and availability", "make repair more explicit when tone gets lost", "send a thoughtful detail that lets them feel included", "plan for the emotional dip after visits", "protect trust through transparency and boundaries", "give yourselves permission to have imperfect communication days", "share future hopes without using them to avoid present needs", "notice effort across the whole week, not a single quiet day", "make ordinary life feel shared through photos, notes, or routines"], questions: ["What rhythm makes both of you feel connected without drained?", "What small part of your day could you share today?", "When is the next moment you can look forward to together?", "What reassurance would feel honest rather than forced?", "What gets lost over text that needs a call?", "How can you keep your independent life healthy too?", "What ritual would make the distance feel more manageable?", "What expectation needs to be spoken clearly?", "How do you both repair after a misread tone?", "What does trust look like in the practical details?", "What is one surprise that would make them feel close?", "How can you make visits feel sustainable rather than perfect?", "What future plan feels grounding, not pressuring?", "What does quality time mean across distance?", "How can you be present with the relationship today?", "What would help you feel chosen this week?" ] },
  "self-esteem": { markers: ["self esteem", "self-esteem", "worth", "hate myself", "not good enough", "insecure"], focus: "self-worth that is practiced, not performed", actions: ["separate a hard moment from a global judgment about yourself", "collect evidence of your character, not only your outcomes", "replace comparison with one action aligned to your values", "speak to yourself as you would to someone you care about", "let a compliment land without arguing with it", "choose clothes, routines, and spaces that support your sense of self", "notice the difference between a need and a flaw", "keep a promise to yourself today, even a small one", "reduce exposure to accounts that trigger comparison", "make room for rest without calling it laziness", "name one strength that has nothing to do with appearance", "practice receiving support without earning it first", "set a boundary that honors your time", "allow yourself to be a beginner", "turn self-talk into something factual and fair", "choose belonging over trying to be universally liked"], questions: ["What evidence of your worth are you overlooking?", "What would you say to someone you loved in this position?", "What value do you show even on a difficult day?", "What promise to yourself would build trust today?", "Where are you comparing instead of observing?", "What does enough look like in this moment?", "What strength has carried you before?", "What boundary would be an act of self-respect?", "What would change if you stopped treating this as a flaw?", "What kind of support do you deserve without earning it?", "What can you do that makes you feel capable?", "How can you make your inner voice more accurate?", "What is one thing you like about how you show up?", "What would help you feel more at home in yourself?", "How can you practice being on your own side?", "What would confidence look like if it were quiet?" ] },
  "body-language": { markers: ["body language", "eye contact", "posture", "body", "nonverbal", "gesture"], focus: "open, grounded body language", actions: ["lower your shoulders and let your hands rest naturally", "make eye contact for a breath, then look away comfortably", "keep your stance balanced and your feet grounded", "face the person you are speaking with when it feels safe", "use a warm, relaxed smile rather than forcing constant expression", "slow your gestures enough to match your words", "uncross your arms when you want to signal openness", "notice whether you are leaning in from interest or tension", "give yourself a comfortable amount of personal space", "take one slow breath before you speak", "let your voice pace match your calmest posture", "use small nods to show you are listening", "keep your phone out of your hands during meaningful conversation", "choose clothes that let you move comfortably", "practice in a mirror only as a tool, not a critique", "return attention to connection instead of monitoring every movement"], questions: ["What would help your body feel safer before you speak?", "Can you soften one place where you are holding tension?", "What posture helps you feel grounded rather than guarded?", "How can your hands support your point naturally?", "What does relaxed eye contact feel like for you?", "Are you giving yourself enough space to breathe?", "What nonverbal signal do you want to send?", "How can you listen with your whole posture?", "What changes when you slow down by ten percent?", "What is one body-language habit you can practice today?", "How can you look interested without over-monitoring yourself?", "What would make your voice sound more settled?", "Where can you replace tension with a steady breath?", "What outfit helps you feel most like yourself?", "Can you let your face rest instead of performing?", "What would open body language look like in this setting?" ] },
};

const reflectionTemplates = [
  "You are not behind; you are learning a skill in real time.",
  "The goal is not a perfect move. It is a respectful, honest next move.",
  "A good conversation is shared work, so you do not have to carry every moment.",
  "Notice what is actually happening before trusting the loudest worry.",
  "You can be warm without abandoning your standards.",
  "The most grounded choice is usually clearer and simpler than the anxious one.",
  "You can allow uncertainty without chasing it for an answer.",
  "Small consistency often says more than one intense moment.",
  "Your feelings are information; they do not have to become instructions.",
  "You deserve connection that feels reciprocal, not exhausting.",
  "Being direct can be kind when you pair it with warmth.",
  "You do not need to earn the right to take up space in a conversation.",
  "You can be curious about someone without making their response your scorecard.",
  "Progress looks like choosing yourself while staying open to connection.",
  "You are allowed to go at a pace that keeps you steady.",
  "You can care deeply and still keep your footing.",
  "A pause is a communication tool, not a failure.",
  "The version of you that is calm and honest is already enough to start.",
];

export const COACH_TEMPLATE_COUNT = (Object.keys(topicProfiles).length * reflectionTemplates.length * 16);

export function detectCoachTopic(input: string, previousTopics: CoachTopic[] = []): CoachTopic {
  const lower = input.toLowerCase();
  const ranked = (Object.entries(topicProfiles) as [CoachTopic, typeof topicProfiles[CoachTopic]][])
    .map(([topic, profile]) => ({ topic, hits: profile.markers.reduce((total, marker) => total + (lower.includes(marker) ? marker.split(" ").length : 0), 0) }))
    .sort((left, right) => right.hits - left.hits);
  return ranked[0]?.hits ? ranked[0].topic : previousTopics[0] ?? "communication";
}

function hash(value: string) {
  return [...value].reduce((total, char) => ((total << 5) - total + char.charCodeAt(0)) | 0, 0) >>> 0;
}

export function createEmptyMemory(userName = ""): CoachMemory {
  return { userName, goals: [], confidenceLevel: "building", favoriteTopics: [], recentResponses: [] };
}

export function normalizeCoachMemory(value: unknown, fallbackName = ""): CoachMemory {
  if (!value || typeof value !== "object") return createEmptyMemory(fallbackName);
  const record = value as Partial<CoachMemory>;
  const allowedTopics = new Set(Object.keys(topicProfiles) as CoachTopic[]);
  return {
    userName: typeof record.userName === "string" ? record.userName.slice(0, 80) : fallbackName,
    goals: Array.isArray(record.goals) ? record.goals.filter((goal): goal is string => typeof goal === "string").map((goal) => goal.slice(0, 120)).slice(0, 8) : [],
    confidenceLevel: record.confidenceLevel === "steady" || record.confidenceLevel === "strong" ? record.confidenceLevel : "building",
    favoriteTopics: Array.isArray(record.favoriteTopics) ? record.favoriteTopics.filter((topic): topic is CoachTopic => typeof topic === "string" && allowedTopics.has(topic as CoachTopic)).slice(0, 6) : [],
    relationshipStatus: typeof record.relationshipStatus === "string" ? record.relationshipStatus.slice(0, 80) : undefined,
    xp: typeof record.xp === "number" && Number.isFinite(record.xp) ? record.xp : 0,
    achievements: Array.isArray(record.achievements) ? record.achievements.filter((achievement): achievement is string => typeof achievement === "string").slice(0, 20) : [],
    recentResponses: Array.isArray(record.recentResponses) ? record.recentResponses.filter((response): response is string => typeof response === "string").slice(-16) : [],
  };
}

export function updateCoachMemory(memory: CoachMemory, prompt: string, topic: CoachTopic, user: { name?: string; xp?: number } = {}): CoachMemory {
  const lower = prompt.toLowerCase();
  const next: CoachMemory = { ...memory, userName: user.name || memory.userName, xp: user.xp ?? memory.xp };
  const goalsMatch = prompt.match(/(?:my goal is|i want to|i'm trying to|i am trying to)\s+([^.!?]{3,90})/i)?.[1]?.trim();
  if (goalsMatch && !next.goals.includes(goalsMatch)) next.goals = [...next.goals, goalsMatch].slice(-8);
  const statusMatch = prompt.match(/(?:i am|i'm)\s+(single|married|engaged|in a relationship|dating someone|seeing someone)/i)?.[1];
  if (statusMatch) next.relationshipStatus = statusMatch.toLowerCase();
  if (/(not confident|insecure|anxious|nervous|shy)/.test(lower)) next.confidenceLevel = "building";
  if (/(confident|proud|better at|improving)/.test(lower)) next.confidenceLevel = "steady";
  if (/(feel great|strong|ready)/.test(lower)) next.confidenceLevel = "strong";
  next.favoriteTopics = [topic, ...next.favoriteTopics.filter((item) => item !== topic)].slice(0, 6);
  return next;
}

export function buildOfflineCoachReply(prompt: string, memory: CoachMemory, thread: CoachTurn[] = []) {
  const topic = detectCoachTopic(prompt, memory.favoriteTopics);
  const profile = topicProfiles[topic];
  const seed = hash(`${prompt}|${memory.userName}|${thread.slice(-4).map((turn) => turn.text).join("|")}|${memory.recentResponses.length}`);
  const candidates = Array.from({ length: 18 }, (_, offset) => {
    const reflection = reflectionTemplates[(seed + offset) % reflectionTemplates.length];
    const action = profile.actions[(seed + offset * 3) % profile.actions.length];
    const question = profile.questions[(seed + offset * 5) % profile.questions.length];
    const personal = memory.userName ? `${memory.userName}, ` : "";
    const goal = memory.goals[0] ? ` Since you want to ${memory.goals[0]}, ` : " ";
    const status = memory.relationshipStatus ? ` With your current relationship status in mind (${memory.relationshipStatus}), ` : " ";
    return `Coach Victor: ${personal}${reflection}${goal}${status}For ${profile.focus}, try this: ${action}. ${question}`.replace(/\s+/g, " ").trim();
  });
  const reply = candidates.find((candidate) => !memory.recentResponses.includes(candidate)) ?? candidates[(seed + memory.recentResponses.length) % candidates.length];
  return { reply, topic };
}

export function coachSystemPrompt(memory: CoachMemory) {
  return `You are Coach Victor for CharmCraft. Give practical, warm, respectful, consent-first conversation coaching. Personalize using this memory: name=${memory.userName || "not provided"}; goals=${memory.goals.join(", ") || "not provided"}; confidence=${memory.confidenceLevel}; relationship status=${memory.relationshipStatus || "not provided"}; favorite topics=${memory.favoriteTopics.join(", ") || "not provided"}; XP=${memory.xp || 0}. Do not diagnose. Do not encourage manipulation. Ask one useful follow-up question. Keep replies under 160 words and never repeat a previous reply.`;
}
